### ISSUE TITLE
Add Part2_new.stp

### ISSUE THREAD

**Issue by PaoloElMarinelo** [KaeptnBalu/Arduino_Spot_Welder_V3#1]
Hi !
First I want to say thank you for all you make in this project, it's the best spot welder I know !
Please could you add the .STP file from Part2_new in Arduino_Spot_Welder_V3/Parts/Aluminum Parts/ ?
Thank you very much.
Paolo

**Comment by KaeptnBalu** [comment]
Hi, 
Thanks for pointing out the missing file. I added it.
