### ISSUE TITLE
V3.3.3 Arduino Code selectedSubMenu not assigned value correctly

### ISSUE THREAD

**Issue by richard-scott** [KaeptnBalu/Arduino_Spot_Welder_V3#11]
I've migrated your code over to using PlatformIO, and I get this error when compiling it:

> Arduino Spot Welder/src/Arduino_Spot_Welder_V3_3_3.ino:539:37: warning: statement has no effect [-Wunused-value]
>                      selectedSubMenu == 0;

It is from this section:
![image](https://user-images.githubusercontent.com/5149834/76706339-a2e65b80-66de-11ea-84d3-c362c980d7f6.png)

My repo is here:
https://github.com/richard-scott/Arduino_Spot_Welder_V3

**Comment by richard-scott** [comment]
I've squashed the error in my repo here:
https://github.com/richard-scott/Arduino_Spot_Welder_V3
I'll create a PR.

**Comment by KaeptnBalu** [comment]
Awesome Job Richard. Thank you so much for your work. This actually fixed the 10.000 welds counter bug. It can now count above 10.000 without creating an error. I will implement your fix in a new V3.3.4 of the spot welder software.
