### ISSUE TITLE
nothing happens when button is pressed

### ISSUE THREAD

**Issue by stefi01** [KaeptnBalu/Arduino_Spot_Welder_V3#16]
the screen works ok and the pot when turned left or right moves up and down through the milliseconds but when pressed to select or set nothing happens, am i missing something, checking the arduino sketch does not reveal any pin numbers so i am a bit lost, this is a home build and not a kit, pcb is ok and was made by jlbpcb.

**Comment by KaeptnBalu** [comment]
The button of the encoder is connected to GNG and pin D6 on the Arduino Nano. When you push it Pin D6 should be pulled to GND.

**Comment by stefi01** [comment]
found it, got it working, thanks :)
